<div class="button-container">
  <div class="action-button back my-2">
    <button type="button" action="action" onclick="history.go(-1)">Retour</button>
  </div>
</div>

<p class="m-3">Enregistrer un nouvel Ordre de travail: </p>
<div class="app-form" id="formulaire">
  <form class="form m-3" action="../pages/add_valid_ot.php" method="post">
    <?php
    foreach ($form->getData() as $key => $value) {
      echo $form->label($key, $value['name']);
      echo $form->input($key, $value['type']);
    }
    ?>

    <label for="plane">Aeronef(s) concerné(s)</label>

    <input type="hidden" id='count_plane' name="count_plane" value="">

    <div id="plane_div" class="my-2">
      <div id="plus-minus-plane">
        <button id="plus_plane" type="button" name="button">
          <i class="fas fa-plus-circle">+</i>
        </button>
      </div>
      <input class="form-control plane_autocomplete" type="text" name="plane0" required></input>
    </div>

    <label for="item">Item(s) concerné(s)</label>

    <input type="hidden" id='count_item' name="count_item" value="">

    <div id="item_div" class="my-2">
      <div id="plus-minus-item">
        <button id="plus_item" type="button" name="button">
          <i class="fas fa-plus-circle">+</i>
        </button>
      </div>
      <input class="form-control item_autocomplete" type="text" name="item0" required></input>
    </div>

    <?php echo $form->submit(); ?>

  </form>
</div>
<script src="js/ot_input_manager.js"></script>
