<div class="button-container">
  <div class="action-button back my-2">
    <button type="button" action="action" onclick="history.go(-1)">Retour</button>
  </div>
</div>

<p class="m-3">Enregistrer un nouveau client: </p>
<div class="app-form">
  <form class="form m-3" action="../pages/add_valid_customers.php" method="post" enctype="multipart/form-data">
    <?php
      foreach ($form->getData() as $key => $value) {
        echo $form->label($key, $value['name']);
        echo $form->input($key, $value['type']);
      }
      echo $form->submit();
    ?>
  </form>
</div>
