<div class="button-container">
  <div class="action-button my-2">
    <a href="index.php?p=modify_supplier&table=supplier&id=<?= $supplier->getDataAbout('supplier_id') ?>">Modifier</a>
  </div>
  <div class="action-button my-2">
    <a href="index.php?p=add_supplier&table=supplier">Ajouter un Fournisseur</a>
  </div>
</div>

<div class="sub-content">
  <h3 class="display-4 mb-4">Entreprise : <?=  $supplier->getDataAbout('company') ?></h3>
  <p><u>Localisation</u> : <?= $supplier->getDataAbout('city').', '. $supplier->getDataAbout('country') ?></p>
  <hr class="my-4">
  <p class="alert alert-warning">Ajouter une liste des Items fournis par l'Entreprise</p>
  <p><u>Email</u> : <?=  $supplier->getDataAbout('email') ?></p>
  <p><u>Téléphone</u> : <?=  $supplier->getDataAbout('indicatif').$supplier->getDataAbout('phone') ?></p>
</div>
