<div class="button-container">
  <div class="action-button my-2">
    <a href="index.php?p=modify_users&table=users&id=<?= $user->getDataAbout('user_id') ?>">Modifier</a>
  </div>
  <div class="action-button my-2">
    <a href="index.php?p=add_users&table=users">Ajouter un Employé</a>
  </div>
</div>

<div class="sub-content">
  <h3 class="display-4 mb-4">Nom : <?=  $user->getDataAbout('fullname') ?></h3>
  <hr class="my-4">
  <p><u>Date d'habilitation</u> : <?=  $user->getDataAbout('skill_date') ?></p>
  <br>
  <p><u>Date de naissance</u> : <?= $user->getDataAbout('birthdate') ?></p>
</div>
