<div class="button-container">
  <div class="action-button my-2">
    <a href="index.php?p=add_items&table=items">Ajouter un Item</a>
  </div>
</div>

<table class="table table-striped table-bordered">

      <?= Table::colTitle(['Part Number', 'Numéro de série' ,'Désignation']); ?>

  <tbody>
    <?php foreach ($table->getData() as $key => $value): ?>
      <tr>
        <td><a href="index.php?p=focus_items&table=items&id=<?= $value->item_id ?>"><?= $value->part_number; ?><a></td>
        <td><?= $value->serial_number_item; ?></td>
        <td><?= $value->designation; ?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
