<!DOCTYPE html>
<html lang="fr" >
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" charset="utf-8"></script>
		<title>App Timizer - Login</title>
	</head>
	<body>
		<div align="center" style=" padding-top:200px;">
			<form method="POST" action="../app/class/auth.php">
				<fieldset>
					<table>
						<tr>
							<td>Login :</td><td><input type="text" name="Login" /></td>
						</tr>
						<tr>
							<td>Password :</td><td><input type="password" name="Password" /></td>
						</tr>
					</table>
				</fieldset>
				<input type="submit" value="    OK    " class="button">
			</form>
		</div>
	</body>
</html>
