<div class="button-container">
  <div class="action-button my-2">
    <a href="index.php?p=add_supplier&table=supplier">Ajouter un Fournisseur</a>
  </div>
</div>

<table class="table table-striped table-bordered">

      <?= Table::colTitle([Table::sort('company','Fournisseur',$_GET) ,'Ville', 'Adresse', 'ZIP', Table::sort('country','Pays',$_GET), 'Téléphone']); ?>

  <tbody>
    <?php foreach ($table->getData() as $key => $value): ?>
      <tr>
        <td><a href="index.php?p=focus_supplier&table=supplier&id=<?= $value->supplier_id ?>"><?= $value->company; ?></a></td>
        <td><?= $value->city; ?></td>
        <td><?= $value->adress; ?></td>
        <td><?= $value->zip_code; ?></td>
        <td><?= $value->country; ?></td>
        <td><?= $value->indicatif.$value->phone; ?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
