<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>App Timizer</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <style>@import url('https://fonts.googleapis.com/css?family=Poppins&display=swap');</style>
  <link rel="stylesheet" href="../public/css/style.css" type="text/css" />
</head>
<!-- BODY -->
<body>
  <header class="header mt-2">
      <div id="header-img" class="text-center mb-3">
          <a href="index.php"><img src="../ressources/apptimizer_logo.png" alt='App Timizer'></a>
      </div>
      <?php if (session_status() === PHP_SESSION_ACTIVE){
        echo '<nav id="navigation" class="navbar navbar-expand-lg navbar-light bg-light border border-primary rounded-lg">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li><a class="mx-1" href="index.php?p=plane&table=plane">Avions</a></li>
                    <li><a class="mx-1" href="index.php?p=items&table=items">Equipements</a></li>
                    <li><a class="mx-1" href="index.php?p=ot&table=ot">Ordres de travail</a></li>
                    <li><a class="mx-1" href="index.php?p=customers&table=customers">Clients</a></li>
                    <li><a class="mx-1" href="index.php?p=users&table=users">Employés</a></li>
                    <li><a class="mx-1" href="index.php?p=supplier&table=supplier">Fournisseurs</a></li>
                  </ul>
                </div>
              </nav>
              <a href="../pages/disconnect.php" class="btn btn-info">Deconnexion</a>';
      } ?>
  </header>
  <main>
    <div class="fixwidth my-4"></div>
    <div class="content">
      <?php echo $content; ?>
    </div>
  </main>
  <!-- FOOTER -->
  <footer class="mt-4">
    <p style="text-align:center; font-size:9px;">App'timizer</p>
    <p style="text-align:center; font-size:9px;">conversin.k.pro@gmail.com</p>
  </footer>

</body>
